CREATE TABLE tasks(
    uuid VARCHAR(128) NOT NULL PRIMARY KEY,
    progress VARCHAR(128) NOT NULL,
);

CREATE TABLE images( 
    id SERIAL PRIMARY KEY,
    task_id  VARCHAR(128) REFERENCES tasks(uuid) ON DELETE CASCADE,
    title VARCHAR(256) NOT NULL
);

CREATE TABLE faces(
    width INTEGER NOT NULL,
    height INTEGER NOT NULL,
    x INTEGER NOT NULL,
    y INTEGER NOT NULL,
    gender varchar(16) NOT NULL,
    age INTEGER NOT NULL,
    image_id INTEGER REFERENCES images(id) ON DELETE CASCADE
);